/**
 * Lookup helpers over the vendored Malaysia postcode dataset
 * (malaysia-postcodes.json, generated by
 * scripts/generate-malaysia-postcodes.mjs). Used by the checkout address
 * form to auto-fill state/area from a typed postcode and to shortlist
 * area options per state.
 */
import data from "./malaysia-postcodes.json";

type Dataset = {
  states: string[];
  postcodes: Record<string, [string, number]>;
};

const dataset = data as unknown as Dataset;

export function lookupPostcode(
  postcode: string,
): { state: string; area: string } | null {
  if (!/^[0-9]{5}$/.test(postcode)) return null;
  const entry = dataset.postcodes[postcode];
  if (!entry) return null;
  const [area, stateIndex] = entry;
  const state = dataset.states[stateIndex];
  if (!state) return null;
  return { state, area };
}

let cachedStates: string[] | null = null;

export function statesList(): string[] {
  cachedStates ??= [...dataset.states].sort((a, b) => a.localeCompare(b));
  return cachedStates;
}

const cachedAreas = new Map<string, string[]>();

export function areasForState(state: string): string[] {
  const hit = cachedAreas.get(state);
  if (hit) return hit;
  const stateIndex = dataset.states.indexOf(state);
  const areas =
    stateIndex === -1
      ? []
      : [
          ...new Set(
            Object.values(dataset.postcodes)
              .filter(([, idx]) => idx === stateIndex)
              .map(([area]) => area),
          ),
        ].sort((a, b) => a.localeCompare(b));
  cachedAreas.set(state, areas);
  return areas;
}
