// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "common": {
    "appName": "AyamNorliza Ops",
    "language": "Language",
    "changeLanguage": "Change language",
    "workspaceSuffix": "{section} workspace",
    "loading": "Loading...",
    "save": "Save",
    "cancel": "Cancel",
    "back": "Back",
    "signOut": "Sign out",
    "toggleTheme": "Toggle color theme",
    "openMenu": "Open menu",
    "closeMenu": "Close menu",
    "userMenu": "User menu"
  },
  "auth": {
    "login": {
      "title": "Sign in to your account",
      "subtitle": "Enter your credentials to access AyamNorliza operations.",
      "emailLabel": "Email",
      "passwordLabel": "Password",
      "submit": "Sign in",
      "submitting": "Signing in...",
      "forgotPassword": "Forgot your password?",
      "noAccount": "Need an account?",
      "signUpLink": "Request access",
      "mfaHint": "Two-factor authentication can be enabled from security settings after sign in."
    },
    "signup": {
      "title": "Create account",
      "subtitle": "New accounts are invite-only. Contact your organization owner if you need access.",
      "emailLabel": "Email",
      "displayNameLabel": "Display name",
      "passwordLabel": "Password (min 12)",
      "submit": "Create account",
      "submitting": "Creating...",
      "haveAccount": "Already have an account?",
      "signInLink": "Sign in",
      "checkEmailTitle": "Check your email",
      "checkEmailBody": "We sent a confirmation link to {email}. Click it to finish setting up your account."
    },
    "mfa": {
      "title": "Two-factor authentication",
      "subtitle": "Enter the 6-digit code from your authenticator app.",
      "codeLabel": "Code",
      "submit": "Verify and enable",
      "submitting": "Verifying...",
      "qrInstructions": "Scan this QR code with your authenticator app, then enter the 6-digit code.",
      "qrAlt": "TOTP QR code",
      "cancel": "Cancel",
      "notEnrolledOptional": "Add an authenticator app to protect your account with an extra layer of security. You can skip for now and enable it later from your security settings.",
      "notEnrolledRequired": "Add an authenticator app to protect your account.",
      "setup": "Set up authenticator app",
      "setupPending": "Starting...",
      "skip": "Skip for now"
    },
    "invite": {
      "title": "Accept your invitation",
      "subtitle": "Set a password to finish joining {organizationName}.",
      "submit": "Accept invitation",
      "submitting": "Accepting...",
      "expired": "This invitation link has expired. Ask your organization owner to send a new one.",
      "failureTitle": "Could not accept invitation"
    },
    "errors": {
      "invalidCredentials": "That email and password combination did not match.",
      "rateLimited": "Too many attempts. Try again in a few minutes.",
      "unexpected": "Something went wrong. Try again."
    }
  },
  "status": {
    "order": {
      "pending": "Pending",
      "confirmed": "Confirmed",
      "ready": "Ready",
      "delivered": "Delivered",
      "closed": "Closed",
      "cancelled": "Cancelled"
    },
    "run": {
      "planned": "In the yard",
      "departed": "On the road",
      "completed": "Back in"
    }
  },
  "buyer": {
    "nav": {
      "shop": "Shop",
      "orders": "Orders",
      "profile": "Profile"
    },
    "header": {
      "brand": "Shop",
      "cart": "Cart",
      "userMenu": "User menu",
      "buyerFallback": "Buyer",
      "myOrders": "My Orders",
      "login": "Log In",
      "menuToggle": "Open menu"
    },
    "cart": {
      "emptyTitle": "Your cart is empty — let's pick some fresh chicken",
      "viewProducts": "View products",
      "sizeLine": "{min}–{max} kg/bird · {fallback}",
      "decrease": "Decrease",
      "increase": "Increase quantity",
      "remove": "Remove",
      "quantityKg": "{quantity} kg",
      "estimatedTotal": "Estimated total",
      "checkout": "Continue to checkout",
      "title": "Your Cart",
      "viewCart": "View cart",
      "barSummary": "{count, plural, one {# item} other {# items}} · {total}"
    },
    "sheet": {
      "close": "Close",
      "defaultTitle": "Sheet"
    },
    "product": {
      "add": "Add",
      "buyBy": "Buy by",
      "unitPiece": "Piece",
      "unitKg": "Kg",
      "quantityPieceLabel": "Quantity (pcs)",
      "quantityKgLabel": "Quantity (kg)",
      "decrease": "Decrease",
      "increase": "Increase quantity",
      "sizeMinLabel": "Min size (kg/bird)",
      "sizeMaxLabel": "Max size (kg/bird)",
      "fallbackLabel": "If size isn't available?",
      "addToCart": "Add to cart",
      "fallback": {
        "cancel": "Cancel my order",
        "mix": "Mix sizes",
        "upsize": "Bigger is fine",
        "downsize": "Smaller is fine"
      }
    },
    "pricing": {
      "perKg": "/kg",
      "perPiece": "/piece",
      "whyEstimate": "Why an estimated price?",
      "weighed": "Weighed {weight} × {pricePerKg}/kg",
      "afterWeighing": "Price after weighing",
      "gotIt": "Got it!",
      "explainer": {
        "chooseTitle": "You choose the chicken",
        "chooseBody": "Pick the size and cut you want.",
        "weighTitle": "We weigh it when it's ready",
        "weighBody": "Every bird is weighed precisely before delivery.",
        "priceTitle": "Price follows actual weight",
        "priceBody": "Final price = actual weight × price/kg. The ~ mark means an estimate."
      }
    },
    "orderTracker": {
      "ariaLabel": "Order status",
      "booked": "Booked",
      "shipped": "Shipped",
      "priceConfirmed": "Price confirmed"
    },
    "shop": {
      "errorTitle": "Catalog unavailable",
      "errorBody": "We couldn't load the catalog. Please try again later.",
      "emptyTitle": "No products",
      "emptyBody": "No products yet — check back soon!",
      "farmEyebrow": "{name} Farm",
      "farmEyebrowFallback": "Our Farm",
      "heroTitle": "Fresh chicken, weighed right.",
      "heroBody": "Choose your chicken today — we weigh it in front of you and confirm the price by actual weight.",
      "categoriesAriaLabel": "Categories",
      "allCategory": "All"
    },
    "login": {
      "loginFailedTitle": "Sign in failed",
      "loginFailedDefault": "Wrong email or password.",
      "welcomeBackToastTitle": "Welcome back!",
      "loggedInDesc": "You're signed in.",
      "passwordMismatchTitle": "Passwords don't match",
      "passwordMismatchDesc": "Make sure both passwords are the same.",
      "passwordTooShortTitle": "Password too short",
      "passwordTooShortDesc": "Password must be at least 8 characters.",
      "signupFailedTitle": "Sign up failed",
      "signupFailedDefault": "Couldn't create your account.",
      "accountCreatedTitle": "Account created!",
      "accountCreatedDesc": "Welcome! You can start shopping.",
      "welcomeBackTitle": "Welcome back",
      "createAccountTitle": "Create account",
      "loginDescription": "Sign in to your buyer account",
      "signupDescription": "Sign up to start shopping",
      "modeAriaLabel": "Account mode",
      "loginTab": "Log in",
      "signupTab": "Sign up",
      "emailLabel": "Email",
      "passwordLabel": "Password",
      "loginPasswordPlaceholder": "Your password",
      "nameLabel": "Name",
      "phoneLabel": "Phone number",
      "phoneHint": "We'll send order updates to this number.",
      "signupPasswordPlaceholder": "At least 8 characters",
      "confirmPasswordLabel": "Confirm password",
      "confirmPasswordPlaceholder": "Repeat password",
      "loggingIn": "Logging in…",
      "signingUp": "Signing up…",
      "continueWithoutAccount": "Continue shopping without an account"
    },
    "checkout": {
      "title": "Checkout",
      "accountHeading": "Your account",
      "signedInAs": "Signed in as {name}",
      "addressHeading": "Delivery address",
      "loadingAddresses": "Loading your addresses...",
      "defaultBadge": "Default",
      "newAddressButton": "+ New address",
      "checkingZone": "Checking zone…",
      "zoneConfirmed": "Zone: {zone} ✓",
      "zoneConfirmedFallback": "Confirmed",
      "zoneUncovered": "We don't cover this area yet — try another postcode or contact us.",
      "zoneError": "Couldn't check the zone right now — try again.",
      "retry": "Try again",
      "slotHeading": "Delivery slot",
      "slotHintNeedAddress": "Fill in your address first to see slots.",
      "slotHintChooseTime": "Choose a date and time.",
      "loadingSlots": "Loading slots…",
      "noSlots": "No slots for this area yet.",
      "dateAriaLabel": "Date",
      "timeAriaLabel": "Time",
      "slotsRemaining": "{count, plural, one {# slot left} other {# slots left}}",
      "addNotes": "+ Add notes",
      "notesPlaceholder": "Any special instructions for your order?",
      "estimateLabel": "Estimate",
      "estimatePlaceholder": "—",
      "submitting": "Submitting…",
      "stageAccount": "Fill in your account",
      "stageAddress": "Choose address",
      "stageSlot": "Choose delivery slot",
      "stageReady": "Place order",
      "emailAlreadyRegisteredTitle": "Email already registered",
      "emailAlreadyRegisteredDesc": "Enter your password to continue.",
      "accountFailedTitle": "Account failed",
      "defaultBuyerNameSignup": "Buyer",
      "defaultBuyerNameSignin": "Customer",
      "sessionExpiredTitle": "Account session expired",
      "sessionExpiredDesc": "Please re-enter your account details and try again.",
      "orderFailedTitle": "Order failed",
      "orderReceivedTitle": "Order received!",
      "orderNumber": "Order no. #{id}",
      "orderReceivedBody": "We'll weigh your chicken and confirm the price before delivery. Your address has been saved for future orders.",
      "viewMyOrders": "View my orders",
      "continueShopping": "Keep shopping",
      "accountRadiogroupLabel": "Account",
      "accountModeNew": "New account",
      "accountModeExisting": "Already have an account",
      "phonePlaceholder": "012-345 6789",
      "passwordMinHint": "(min 8 characters)"
    },
    "orders": {
      "errorLoad": "Failed to load orders.",
      "subtitle": "Your order history",
      "emptyTitle": "No orders yet",
      "emptyBody": "Let's start shopping!",
      "orderNumber": "Order #{id}",
      "deliveryPrefix": "Delivery:",
      "viewDetails": "View details"
    },
    "orderDetail": {
      "title": "Order Details",
      "statusCardTitle": "Order Status",
      "bookedAt": "Booked {date}",
      "cancelledNotice": "This order has been cancelled.",
      "itemsCardTitle": "Items",
      "unknownProduct": "Unknown product",
      "itemCancelledBadge": "Cancelled",
      "quantityPieces": "{count, plural, one {# bird} other {# birds}}",
      "sizeRange": "{min}-{max} kg/bird",
      "fallbackUsed": "Used: {note}",
      "weighedConfirmed": "Weighed and price confirmed ✓",
      "total": "Total",
      "addressCardTitle": "Delivery Address",
      "notesCardTitle": "Order Notes",
      "error": "Error",
      "cancelOrder": "Cancel order",
      "cancelling": "Cancelling...",
      "cancelDialogTitle": "Cancel this order?",
      "cancelDialogDescription": "This cannot be undone. Let us know why (optional).",
      "cancelReasonPlaceholder": "Reason (optional)",
      "keepOrder": "Keep order",
      "orderCancelledToast": "Order cancelled"
    },
    "profile": {
      "title": "My Profile",
      "cardTitle": "Personal Information",
      "cardDescription": "Update your profile information and delivery address.",
      "displayNameLabel": "Display Name",
      "displayNamePlaceholder": "Your name",
      "phoneLabel": "Phone Number",
      "phonePlaceholder": "Your phone number",
      "addressLabel": "Default Delivery Address",
      "addressPlaceholder": "Your default delivery address",
      "addressHint": "This address will be used as the default for your orders.",
      "signOut": "Sign Out",
      "saveChanges": "Save Changes",
      "errorTitle": "Error",
      "loadFailedDesc": "Failed to load profile. Please sign in.",
      "profileSavedTitle": "Profile saved",
      "profileSavedDesc": "Your profile has been updated.",
      "saveFailedDefaultDesc": "Failed to save profile."
    }
  },
  "errors": {
    "buyer": {
      "signup": {
        "invalid": "Invalid signup",
        "invalidPhone": "Enter a Malaysian mobile number, e.g. 012-345 6789",
        "orgNotFound": "Shop not found.",
        "createFailed": "Could not create account. Please try again.",
        "profileSaveFailed": "Could not save buyer profile. Please try again.",
        "alreadyRegistered": "This email is already registered. Please log in.",
        "profileCheckFailed": "Could not check buyer profile. Please try again."
      },
      "login": {
        "invalid": "Invalid login",
        "invalidCredentials": "Incorrect email or password.",
        "notABuyer": "This account is not registered as a buyer."
      },
      "account": {
        "wrongOrg": "This account is not a buyer for this shop."
      },
      "catalog": {
        "orgNotFound": "Organization not found",
        "fetchFailed": "Failed to fetch catalog",
        "productNotFound": "Product not found"
      },
      "profile": {
        "unauthenticated": "Not authenticated",
        "notFound": "Buyer profile not found",
        "invalidInput": "Invalid input",
        "updateFailed": "Failed to update profile"
      },
      "address": {
        "invalidAddress": "Invalid address",
        "loadFailed": "Failed to load addresses",
        "saveFailed": "Failed to save address",
        "invalidId": "Invalid address id",
        "notFound": "Address not found",
        "deleteFailed": "Failed to delete address",
        "unauthenticated": "Not authenticated",
        "notABuyer": "Not registered as a buyer"
      },
      "order": {
        "unauthenticated": "Not authenticated",
        "orgNotFound": "Organization not found",
        "invalidInput": "Invalid order input",
        "customerIdNotAllowed": "customerId is not allowed for portal orders",
        "zoneNotFound": "That delivery zone was not found.",
        "slotNotFound": "That delivery slot is no longer available.",
        "dateOutOfWindow": "Pick a delivery date within the next 14 days.",
        "weekdayMismatch": "That date does not match the slot's day of the week.",
        "dateBlocked": "Deliveries are blocked on that date. Pick another.",
        "slotFull": "That delivery slot just filled up — pick another.",
        "invalidItems": "One or more items in your order are invalid.",
        "invalidStatus": "This order can no longer be cancelled.",
        "forbidden": "You cannot cancel this order.",
        "internal": "Something went wrong. Please try again."
      }
    },
    "identity": {
      "common": {
        "unauthenticated": "Sign in first",
        "forbidden": "Insufficient role",
        "notMember": "Not a member of this organization",
        "reauthRequired": "Step-up re-authentication required",
        "internal": "Something went wrong. Please try again.",
        "invalidInput": "Invalid input"
      },
      "organization": {
        "invalidUpdate": "Invalid organization update",
        "updateForbidden": "Insufficient role to update organization settings"
      },
      "invite": {
        "invalidInput": "Invalid invitation input",
        "notFound": "Invitation not found",
        "alreadyAccepted": "Already accepted",
        "revoked": "Revoked",
        "roleCannotInvite": "Role cannot invite users",
        "createFailed": "Could not create the invitation. Please try again.",
        "expired": "Invitation expired",
        "acceptFailed": "Failed to accept invitation",
        "createFailedUnknown": "Failed to create invitation"
      },
      "member": {
        "notFound": "Member not found",
        "alreadyHasRole": "Member already has that role",
        "ownerNeedsApprover": "Owner changes require a second approver",
        "transferOwnershipFirst": "Transfer ownership before deactivating the owner"
      },
      "accessReview": {
        "itemNotFound": "Review item not found",
        "reviewNotFound": "Review not found"
      },
      "supportSession": {
        "notFound": "Session not found",
        "alreadyEnded": "Already ended"
      },
      "breakGlass": {
        "cannotOpen": "Role cannot open break-glass"
      },
      "roles": {
        "notEditable": "Role '{role}' is not editable",
        "capabilityLocked": "Capability '{capability}' is locked",
        "ownerOnlyEdit": "Only the owner can edit capabilities",
        "ownerOnlyReset": "Only the owner can reset capabilities",
        "cannotGrantRole": "Cannot grant role '{role}'",
        "saveOverrideFailed": "Failed to save override"
      },
      "auth": {
        "invalidLogin": "Invalid login",
        "invalidCredentials": "Invalid email or password",
        "invalidReauthInput": "Invalid reauth input",
        "passwordMismatch": "Password did not match",
        "mfaCodeRequired": "MFA code is required",
        "mfaCodeMismatch": "MFA code did not match",
        "invalidSignup": "Invalid signup",
        "signupFailed": "Could not create your account. Please try again.",
        "alreadyRegistered": "This email is already registered.",
        "mfaVerifyFailed": "The verification code did not match. Please try again."
      }
    },
    "drive": {
      "run": {
        "unauthenticated": "Not authenticated",
        "orgNotFound": "Organization not found",
        "forbidden": "You do not have access to this feature",
        "loadFailed": "Failed to load the run",
        "internal": "Something went wrong. Please try again."
      }
    }
  },
  "dashboard": {
    "sections": {
      "sales": "Sales",
      "accessControl": "Access control",
      "warehouse": "Warehouse",
      "system": "System"
    },
    "pages": {
      "products": "Products",
      "orders": "Orders",
      "customers": "Customers",
      "marketPrices": "Market Prices",
      "deliverySetup": "Delivery setup",
      "dispatch": "Dispatch",
      "loading": "Loading",
      "deliveryRuns": "Delivery runs",
      "warehouseTasks": "Warehouse tasks",
      "organization": "Organization",
      "users": "Users",
      "roles": "Roles",
      "accessReviews": "Access reviews",
      "supportSessions": "Support sessions",
      "auditLog": "Audit log",
      "dataConsole": "Data console"
    },
    "fallbackUserName": "Team member"
  },
  "roles": {
    "owner": "Owner",
    "org_admin": "Org Admin",
    "seller": "Seller",
    "driver": "Driver",
    "inventory": "Inventory",
    "logistics": "Logistics",
    "farm_manager": "Farm Manager",
    "supervisor": "Supervisor",
    "caretaker": "Caretaker",
    "veterinarian": "Veterinarian",
    "biosecurity_qa": "Biosecurity QA",
    "maintenance": "Maintenance",
    "auditor": "Auditor",
    "support": "Support"
  },
  "settings": {
    "organization": {
      "title": "Organization settings",
      "description": "Manage your organization's identity and defaults.",
      "unsavedChanges": "Unsaved changes",
      "saved": "Saved",
      "saveChanges": "Save changes",
      "saving": "Saving..."
    },
    "users": {
      "title": "Users"
    },
    "userDetail": {
      "title": "Member"
    },
    "auditLog": {
      "title": "Audit log",
      "description": "Append-only record of every privileged action. Most recent first.",
      "statEvents": "Events",
      "statActors": "Actors",
      "statDistinct": "Distinct"
    },
    "accessReviews": {
      "title": "Access reviews"
    },
    "supportSessions": {
      "title": "Support sessions"
    },
    "security": {
      "title": "My security"
    }
  },
  "identity": {
    "memberStatus": {
      "invited": "Invited",
      "active": "Active",
      "suspended": "Suspended",
      "expired": "Expired"
    },
    "invitationStatus": {
      "accepted": "accepted",
      "revoked": "revoked",
      "expired": "expired",
      "pending": "pending"
    },
    "securityPanel": {
      "signedInAs": "Signed in as {name}"
    },
    "accessReviews": {
      "startReview": "Start quarterly review",
      "starting": "Starting...",
      "reviewHeading": "Review {id} - {status}",
      "due": "Due: {date}",
      "colMember": "Member",
      "colDecision": "Decision",
      "colDecidedAt": "Decided at",
      "colActions": "Actions",
      "notDecided": "-",
      "decision": {
        "keep": "Keep",
        "modify": "Modify",
        "revoke": "Revoke",
        "pending": "pending"
      }
    },
    "supportSessions": {
      "openButton": "Open support session",
      "colPurpose": "Purpose",
      "colTechnician": "Technician",
      "colWindow": "Window",
      "colStatus": "Status",
      "colActions": "Actions",
      "window": "{start} → {end}",
      "end": "End",
      "dialogTitle": "Open support session",
      "sponsorLabel": "Sponsor",
      "technicianLabel": "Technician user id",
      "purposeLabel": "Purpose",
      "durationLabel": "Duration (hours, max 24)",
      "cancel": "Cancel",
      "opening": "Opening...",
      "open": "Open",
      "status": {
        "scheduled": "scheduled",
        "active": "active",
        "ended": "ended",
        "revoked": "revoked"
      }
    },
    "userDetail": {
      "userIdLabel": "User id:",
      "statusLabel": "Status:",
      "roleLabel": "Role",
      "reasonLabel": "Reason",
      "saveRole": "Save role",
      "deactivate": "Deactivate",
      "scopesHeading": "Scopes ({count})",
      "scopeSite": "site {id}",
      "scopeZone": "zone {id}",
      "scopeHouse": "house {id}",
      "scopeOrgWide": "org-wide",
      "scopePermissionSuffix": " - {permission}",
      "defaultReason": "Updated via member detail",
      "defaultDeactivateReason": "Deactivated from member detail"
    },
    "usersPage": {
      "inviteUser": "Invite user",
      "membersHeading": "Members ({count})",
      "colUser": "User",
      "colRole": "Role",
      "colStatus": "Status",
      "colScopes": "Scopes",
      "colActions": "Actions",
      "deactivate": "Deactivate",
      "invitationsHeading": "Invitations ({count})",
      "colEmail": "Email",
      "resend": "Resend",
      "revoke": "Revoke",
      "defaultRoleChangeReason": "Role change via users page",
      "defaultDeactivateReason": "Deactivated from users page"
    },
    "auditLog": {
      "filtersLabel": "Filters",
      "eventTypePlaceholder": "Event type",
      "allEvents": "All events",
      "entityPlaceholder": "Entity",
      "allEntities": "All entities",
      "sourcePlaceholder": "Source",
      "anySource": "Any source",
      "searchPlaceholder": "Search actor, reason, id…",
      "clear": "Clear ({count})",
      "showing": "Showing {shown} of {total} events",
      "appendOnlyNote": "Append-only · tamper-evident · most recent first",
      "today": "Today",
      "yesterday": "Yesterday",
      "eventCount": "{count, plural, one {# event} other {# events}}",
      "emptyTitle": "No audit events match",
      "emptyBody": "Try clearing filters or widening the search query.",
      "copied": "copied",
      "systemActor": "system",
      "detailEventId": "Event ID",
      "detailEntity": "Entity",
      "detailSource": "Source",
      "detailActor": "Actor",
      "detailActorRole": "role: {role}",
      "detailCorrelation": "Correlation",
      "detailReason": "Reason",
      "detailChanges": "Changes",
      "before": "Before",
      "after": "After",
      "noValue": "—",
      "appendOnlyFooter": "This event is append-only. It cannot be edited or deleted from the UI.",
      "closeDetailAria": "Close detail",
      "entryTitleSr": "Audit log entry",
      "classify": {
        "removal": "Removal",
        "anomaly": "Anomaly",
        "privileged": "Privileged",
        "change": "Change",
        "auth": "Auth",
        "event": "Event"
      }
    },
    "rolesPage": {
      "title": "Roles & permissions",
      "editingAsOwner": "Editing as owner",
      "readOnly": "Read only",
      "saved": "Saved",
      "syncing": "Syncing",
      "description": "Decide what each role can do in this organization. Owners can override any capability on any non-owner role. Overrides are recorded in the audit log.",
      "statsRoles": "{count, plural, one {# role} other {# roles}}",
      "statsCapabilities": "{count, plural, one {# capability} other {# capabilities}}",
      "statsOverrides": "{count, plural, one {# override} other {# overrides}}",
      "statsLastEdited": " · last {time}",
      "errorTitle": "Couldn't apply changes",
      "rolesCardTitle": "Roles",
      "rolesCardDesc": "Pick a role to inspect its capability set.",
      "grantedOn": "{count} on",
      "legendTitle": "Legend",
      "legendOn": "On (matches the canonical matrix)",
      "legendOverride": "Override (changed by an owner, recorded in audit)",
      "legendOff": "Off (default or overridden)",
      "legendLocked": "Locked (cannot be removed)",
      "legendLockedBadge": "Locked",
      "capabilitiesEnabled": "{granted} / {total} capabilities enabled",
      "resetToDefaults": "Reset to defaults",
      "ownerLocked": "Owner locked",
      "overridesBadge": "{count, plural, one {# override} other {# overrides}}",
      "roleLocked": "Role locked",
      "grantedByOverride": "Granted by override",
      "revokedByOverride": "Revoked by override",
      "toggleOn": "On",
      "toggleOff": "Off",
      "tooltipEnabled": "Enabled",
      "tooltipDisabled": "Disabled",
      "actionGrant": "grant",
      "actionRevoke": "revoke",
      "toggleTooltip": "{state} — click to {action}",
      "toggleAriaLabel": "Toggle {label} for {role}",
      "lockedReasonOwner": "Owner receives every capability by structure. Cannot be edited.",
      "lockedReasonRoleLocked": "This role is locked.",
      "lockedReasonNotOverridable": "This capability is preserved on every role that needs it. It cannot be removed.",
      "rank": "rank {rank}",
      "areas": {
        "organization": {
          "label": "Organization",
          "description": "Settings that govern the organization as a whole."
        },
        "membership": {
          "label": "Membership",
          "description": "Inviting users, changing roles, scopes, and access lifecycle."
        },
        "access_review": {
          "label": "Access reviews",
          "description": "Periodic attestations that confirm membership and roles."
        },
        "support": {
          "label": "Support sessions",
          "description": "Time-bound elevated access for technicians."
        },
        "break_glass": {
          "label": "Break-glass",
          "description": "Emergency override events recorded to the audit log."
        },
        "audit": {
          "label": "Audit & security",
          "description": "Read access to immutable history and security events."
        }
      },
      "grantTitle": "Grant capability",
      "revokeTitle": "Revoke capability",
      "dialogDescGrant": "Granting this capability adds it on top of the default matrix.",
      "dialogDescRevoke": "Removing this capability overrides the default for this role.",
      "onRole": "on role {role}.",
      "reasonLabel": "Reason (required, audit-visible)",
      "reasonPlaceholder": "e.g. Vet assistants need read access to run reports",
      "reasonHint": "Min 10 characters. This reason is recorded in the audit log alongside the change.",
      "cancel": "Cancel",
      "grant": "Grant",
      "revoke": "Revoke",
      "resetTitle": "Reset role to defaults",
      "resetDescription": "All overrides for {role} will be removed and the role will inherit the canonical capability matrix again.",
      "resetInfo": "Each removal is recorded individually in the audit log so you can recover the previous state if needed.",
      "resetReasonLabel": "Reason (required)",
      "resetReasonPlaceholder": "e.g. Reverting to baseline for Q3 audit",
      "resetButton": "Reset"
    },
    "capabilityMatrix": {
      "heading": "The matrix",
      "subheading": "{roleCount, plural, one {# role} other {# roles}} × {capCount, plural, one {# capability} other {# capabilities}}",
      "description": "Each row is a role, ordered by privilege from top to bottom. Each column is a capability, grouped by category. A filled marker means the role holds that capability; an open marker means it does not.",
      "caption": "Capability matrix for this organization, ordered by role rank.",
      "roleColumnHeader": "Role",
      "cellAriaLabel": "{role} {hasCapability, select, true {has} other {does not have}} capability {capability}"
    },
    "invitationsQueue": {
      "heading": "The invitations queue",
      "summary": "{pending, plural, one {# pending} other {# pending}} · {accepted, plural, one {# accepted} other {# accepted}} · {revoked, plural, one {# revoked} other {# revoked}}",
      "description": "People who have been invited but haven't completed onboarding yet. Acceptance is owned by the invitee; revoking lives in MOD-19.",
      "empty": "Nothing waiting. Every invitation has been accepted or revoked.",
      "expires": "expires {date}"
    },
    "rankLadder": {
      "heading": "The rank ladder",
      "rangeLabel": "0–100",
      "descriptionPrefix": "No role may grant a rank higher than its own. The ladder runs from",
      "descriptionMiddle": "at the floor to",
      "descriptionSuffix": "at the ceiling."
    },
    "roleRoster": {
      "heading": "The roster",
      "activeCount": "{count, plural, one {# active} other {# active}}",
      "description": "People who currently hold each role. Empty rows mean no one holds that role at the moment."
    },
    "rolesMasthead": {
      "kicker": "Access control — {organizationName}",
      "issueTag": "Issue 01 · Phase 1 read-only",
      "titleRoles": "Roles",
      "titlePermissions": "Permissions",
      "description": "A read-only spread of every role inside this organization and every capability each role is granted. Editing this matrix is owned by MOD-19 — until then, this page is the canonical picture.",
      "statRoles": "Roles",
      "statCapabilities": "Capabilities",
      "statCategories": "Categories",
      "lastRevised": "Last revised {date}"
    },
    "updateOrganizationForm": {
      "cardTitle": "General",
      "cardDescription": "Public-facing display and identity for your organization.",
      "errorTitle": "Couldn't save changes",
      "nameLabel": "Name",
      "nameDescription": "The display name shown across the app.",
      "legalNameLabel": "Legal name",
      "legalNameDescription": "Used on contracts and invoices.",
      "regionLabel": "Region",
      "regionDescription": "Helps with date and time defaults.",
      "localizationSectionLabel": "Localization",
      "timezoneLabel": "Default time zone",
      "timezonePlaceholder": "Select a time zone",
      "localeLabel": "Default locale",
      "localePlaceholder": "Select a locale",
      "cancel": "Cancel",
      "saving": "Saving...",
      "saved": "Saved",
      "saveChanges": "Save changes"
    },
    "inviteUserDialog": {
      "title": "Invite a user",
      "emailLabel": "Email",
      "roleLabel": "Role",
      "cancel": "Cancel",
      "sending": "Sending...",
      "sendInvite": "Send invite"
    },
    "breakGlassDialog": {
      "title": "Open break-glass access",
      "description": "This grants you short-window elevated access. Owners are notified within 60 seconds.",
      "reasonLabel": "Reason (10-500 chars)",
      "ticketLabel": "Ticket reference (optional)",
      "durationLabel": "Duration (minutes, max 60)",
      "cancel": "Cancel",
      "opening": "Opening...",
      "open": "Open",
      "reauthRequired": "Please re-authenticate first"
    },
    "reauthDialog": {
      "title": "Confirm it's you",
      "description": "For your security, this action requires recent re-authentication.",
      "passwordLabel": "Password",
      "totpLabel": "6-digit code (if MFA enabled)",
      "cancel": "Cancel",
      "verifying": "Verifying...",
      "confirm": "Confirm",
      "retryFailed": "Action failed after re-auth"
    }
  },
  "drive": {
    "cantOpenRunTitle": "Can't open the run",
    "noRunTitle": "No run for you today",
    "noRunDescription": "The office has not put you on a truck yet. This page will show the run as soon as they do."
  },
  "email": {
    "invite": {
      "subject": "You are invited to {organizationName}",
      "bodyHtml": "<p>{inviterName} invited you to join <strong>{organizationName}</strong> as <strong>{role}</strong>.</p><p>This invitation expires {expiresAt}.</p><p><a>Accept invitation</a></p>"
    },
    "mfaEnrolled": {
      "subject": "Two-factor authentication enabled",
      "bodyHtml": "<p>Two-factor authentication was enabled on your AyamNorliza account.</p><p>If this was not you, contact your organization owner immediately.</p>"
    },
    "breakGlassUsed": {
      "subject": "[{organizationName}] Break-glass access used",
      "bodyHtml": "<p><strong>{userEmail}</strong> used break-glass access in <strong>{organizationName}</strong>.</p><p><strong>Reason:</strong> {reason}</p><p><strong>Ticket:</strong> {ticketReference}</p><p><strong>Expires:</strong> {expiresAt}</p><p>A post-use review is required after the session ends.</p>"
    },
    "temporaryAccessExpiring": {
      "subject": "Temporary access expiring soon",
      "bodyHtml": "<p>Your temporary access to <strong>{organizationName}</strong> expires on {expiresAt}.</p><p>Ask your organization owner to renew it if you still need access.</p>"
    },
    "supportSessionOpened": {
      "subject": "Support session opened in {organizationName}",
      "bodyHtml": "<p>A support session has been opened for you in <strong>{organizationName}</strong>.</p><p><strong>Purpose:</strong> {purpose}</p><p><strong>Window:</strong> {startsAt} → {endsAt}</p>"
    }
  }
};
export default messages;