// Bundled avatar preset faces (Open Peeps, CC0), generated by
// scripts/generate-avatar-presets.mjs into public/avatars/presets/.

export const AVATAR_PRESET_IDS: readonly string[] = Array.from(
  { length: 64 },
  (_, i) => `face-${String(i + 1).padStart(2, "0")}`,
);

export function presetUrl(id: string): string {
  return `/avatars/presets/${id}.svg`;
}
